; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.43"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[quebec][download][type] = ""
projects[quebec][download][url] = ""
projects[quebec][type] = "module"

projects[views_bulk_operations][version] = "3.3"

projects[addthis][version] = "4.0-alpha6"

projects[admin_menu][version] = "3.0-rc5"

projects[admin_views][version] = "1.5"

projects[advanced_link][version] = "1.3"

projects[autoarch][version] = "1.1"

projects[better_formats][version] = "1.0-beta2"

projects[ctools][version] = "1.9"

projects[ckeditor][version] = "1.17"

projects[coffee][version] = "2.2+7-dev"

projects[conditional_fields][version] = "3.0-alpha2"

projects[ctools_api][version] = "1.x-dev"

projects[facetapi][version] = "1.5"

projects[cxense][version] = "1.0"

projects[date][version] = "2.9"
projects[date][patches][0] = "https://s3-us-west-2.amazonaws.com/drupal-platform/patches/date-clone-reserved-keyword-2533080-2.patch"

projects[datepicker][version] = "1.0"

projects[devel][version] = "1.5"

projects[diff][version] = "3.2"

projects[domain][version] = "3.12"

projects[domain_ctools][version] = "1.3"

projects[entity][version] = "1.6"
projects[entity][patches][0] = "https://www.drupal.org/files/issues/entity-speedup-revert.patch"
projects[entity][patches][1] = "https://www.drupal.org/files/issues/entity-speedup-revert.patch"

projects[entity_view_mode][version] = "1.0-rc1"

projects[entityreference][version] = "1.1"
projects[entityreference][patches][0] = "https://www.drupal.org/files/issues/entityreference-1836106-20.patch"
projects[entityreference][patches][1] = "https://www.drupal.org/files/issues/entityreference-restricted_access-21534630-6.patch"

projects[features_extra][version] = "1.0"

projects[features][version] = "2.7"

projects[features_translations][version] = "2.0"

projects[ffc][version] = "1.0-beta2"

projects[field_collection][version] = "1.0-beta11"

projects[field_formatter_settings][version] = "1.1"

projects[field_group][version] = "1.5"

projects[file_entity][version] = "2.0-beta2"

projects[file_md5][version] = "1.4"

projects[google_analytics][version] = "2.1"

projects[i18n][version] = "1.13"

projects[panels][version] = "3.5"

projects[imce][version] = "1.9"

projects[jquery_colorpicker][version] = "1.2"

projects[jquery_update][version] = "2.7"

projects[l10n_update][version] = "2.0"

projects[libraries][version] = "2.2"

projects[link][version] = "1.4"

projects[linkit][version] = "3.5"

projects[mailsystem][version] = "2.34"
projects[mailsystem][patches][0] = "http://www.drupal.org/files/mailsystem.1534706.6.patch"

projects[managed_file][version] = "1.1"

projects[maxlength][version] = "3.2"

projects[media][version] = "2.0-beta1"

projects[media_oembed][version] = "2.5"

projects[menu_attributes][version] = "1.0"

projects[menu_image][version] = "1.0"

projects[metatag][version] = "1.13"

projects[module_filter][version] = "2.0"

projects[node_export][version] = "3.1"

projects[panelizer][version] = "3.1"

projects[panels_everywhere][version] = "1.0-rc2"

projects[pathauto][version] = "1.3"

projects[redirect][version] = "1.0-rc3"

projects[references_dialog][version] = "1.0-beta1"

projects[scheduler][version] = "1.4"

projects[search_api][version] = "1.16"

projects[search_api_db][version] = "1.5"

projects[search_api_override][version] = "1.0-rc1"

projects[search_api_solr][version] = "1.9"

projects[seckit][version] = "1.9"

projects[strongarm][version] = "2.0"
projects[strongarm][patches][0] = "http://drupal.org/files/strongarm-2076543-import-export-value-alter-hooks.patch"

projects[subfolders_domain][version] = "2.8"

projects[table_element][version] = "1.0-beta5"

projects[tablefield][version] = "2.4"

projects[token][version] = "1.6"

projects[uuid][version] = "1.0-beta1"
projects[uuid][patches][0] = "http://drupal.org/files/uuid_services_field_collection_revisions.patch"

projects[uuid_features][version] = "1.0-alpha4"

projects[variable][version] = "2.5"

projects[views][version] = "3.13"

projects[views_show_more][version] = "2.0"

projects[webform][version] = "3.24"

; Themes
projects[adminimal_theme][version] = "1.24"
